#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

feh --bg-scale ~/Downloads/lsd.png
setxkbmap -option "grp:alt_shift_toggle" us,ru
$HOME/.config/polybar/launch.sh &
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 2
bspc config window_gap 10

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focused_border_color "#b998f5"
bspc config border_width 4

bspc rule -a Gimp desktop='^8' state=floating follow=on
