#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

feh --bg-scale ~/Downloads/lsd.png
setxkbmap -option "grp:alt_shift_toggle" us,ru
$HOME/.config/polybar/launch.sh &
wal -R -e &
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 2
bspc config window_gap 10

. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color "$color0"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color2"
bspc config presel_feedback_color "$color1"

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config border_width 4

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a floating_picker state=floating sticky=on center=on rectangle=1000x600+0+0
